/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author megap
 */
public class frmBienvenida extends javax.swing.JFrame {
    
    //Atributos de frmBienvenida
    private frmLogin frmLogin;
    private frmRegister frmRegister;

    /**
     * Creates new form frmInicio
     */
    public frmBienvenida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBienvenida1 = new javax.swing.JPanel();
        pnlBienvenida2 = new javax.swing.JPanel();
        btnAcceder = new javax.swing.JButton();
        btnRegistrarse = new javax.swing.JButton();
        labelEleccion = new javax.swing.JLabel();
        imgCliente = new javax.swing.JLabel();
        labelBienvenida = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bienvenido a Telefonia");
        setMaximumSize(new java.awt.Dimension(868, 612));
        setMinimumSize(new java.awt.Dimension(868, 612));

        pnlBienvenida1.setBackground(new java.awt.Color(0, 102, 102));
        pnlBienvenida1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        pnlBienvenida1.setMaximumSize(new java.awt.Dimension(868, 612));
        pnlBienvenida1.setMinimumSize(new java.awt.Dimension(868, 612));
        pnlBienvenida1.setName(""); // NOI18N

        pnlBienvenida2.setBackground(new java.awt.Color(255, 255, 255));
        pnlBienvenida2.setMaximumSize(new java.awt.Dimension(660, 440));
        pnlBienvenida2.setMinimumSize(new java.awt.Dimension(660, 400));
        pnlBienvenida2.setName("ola"); // NOI18N
        pnlBienvenida2.setPreferredSize(new java.awt.Dimension(660, 400));

        btnAcceder.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnAcceder.setForeground(new java.awt.Color(0, 0, 0));
        btnAcceder.setText("Acceder");
        btnAcceder.setMaximumSize(new java.awt.Dimension(100, 50));
        btnAcceder.setMinimumSize(new java.awt.Dimension(100, 50));
        btnAcceder.setPreferredSize(new java.awt.Dimension(100, 50));
        btnAcceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccederActionPerformed(evt);
            }
        });

        btnRegistrarse.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnRegistrarse.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrarse.setText("Registrarse");
        btnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseActionPerformed(evt);
            }
        });

        labelEleccion.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        labelEleccion.setForeground(new java.awt.Color(0, 0, 0));
        labelEleccion.setText("Seleccione una opción a continuación:");

        imgCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cliente.png"))); // NOI18N

        javax.swing.GroupLayout pnlBienvenida2Layout = new javax.swing.GroupLayout(pnlBienvenida2);
        pnlBienvenida2.setLayout(pnlBienvenida2Layout);
        pnlBienvenida2Layout.setHorizontalGroup(
            pnlBienvenida2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBienvenida2Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(btnAcceder, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrarse)
                .addGap(65, 65, 65))
            .addGroup(pnlBienvenida2Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(labelEleccion)
                .addContainerGap(129, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBienvenida2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imgCliente)
                .addGap(222, 222, 222))
        );
        pnlBienvenida2Layout.setVerticalGroup(
            pnlBienvenida2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBienvenida2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(labelEleccion)
                .addGap(18, 18, 18)
                .addComponent(imgCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(pnlBienvenida2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAcceder, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        labelBienvenida.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        labelBienvenida.setForeground(new java.awt.Color(255, 255, 255));
        labelBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBienvenida.setText("Bienvenido a Telefonia");

        javax.swing.GroupLayout pnlBienvenida1Layout = new javax.swing.GroupLayout(pnlBienvenida1);
        pnlBienvenida1.setLayout(pnlBienvenida1Layout);
        pnlBienvenida1Layout.setHorizontalGroup(
            pnlBienvenida1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBienvenida1Layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addComponent(pnlBienvenida2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
            .addGroup(pnlBienvenida1Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(labelBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBienvenida1Layout.setVerticalGroup(
            pnlBienvenida1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBienvenida1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(labelBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlBienvenida2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBienvenida1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBienvenida1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Metodos getters y setters
    public frmLogin getFrmLogin() {
        return frmLogin;
    }
    public void setFrmLogin(frmLogin frmLogin) {
        this.frmLogin = frmLogin;
    }
    public frmRegister getFrmRegister() {
        return frmRegister;
    }
    public void setFrmRegister(frmRegister frmRegister) {
        this.frmRegister = frmRegister;
    }
  
    //Boton que abre frmLogin
    private void btnAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccederActionPerformed
        // TODO add your handling code here:
        if (frmLogin == null) {
        frmLogin = new frmLogin();
        frmLogin.setFrmBienvenida(this);
        }
        frmLogin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAccederActionPerformed

    //Boton que abre frmRegister
    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
        // TODO add your handling code here:
        if (frmRegister == null) {
        frmRegister = new frmRegister();
        frmRegister.setFrmBienvenida(this);
        }
        frmRegister.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegistrarseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBienvenida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceder;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JLabel imgCliente;
    private javax.swing.JLabel labelBienvenida;
    private javax.swing.JLabel labelEleccion;
    private javax.swing.JPanel pnlBienvenida1;
    private javax.swing.JPanel pnlBienvenida2;
    // End of variables declaration//GEN-END:variables
}
