/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author megap
 */
public class frmBienvenida extends javax.swing.JFrame {
    
    private frmLoginEmpleado frmLoginEmpleado;
    private frmLoginCliente frmLoginCliente;
    private frmRegisterCliente frmRegisterCliente;

    /**
     * Creates new form frmInicio
     */
    public frmBienvenida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBeinvenida1 = new javax.swing.JPanel();
        panelBienvenidos2 = new javax.swing.JPanel();
        labelImgEmpleado = new javax.swing.JLabel();
        labelImgCliente = new javax.swing.JLabel();
        btnEmpleado = new javax.swing.JButton();
        btnCliente = new javax.swing.JButton();
        labelEleccion = new javax.swing.JLabel();
        labelBienvenidos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bienvenido a Telefonia");
        setMaximumSize(new java.awt.Dimension(868, 612));
        setMinimumSize(new java.awt.Dimension(868, 612));

        panelBeinvenida1.setBackground(new java.awt.Color(0, 102, 102));
        panelBeinvenida1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        panelBeinvenida1.setMaximumSize(new java.awt.Dimension(868, 612));
        panelBeinvenida1.setMinimumSize(new java.awt.Dimension(868, 612));
        panelBeinvenida1.setName(""); // NOI18N

        panelBienvenidos2.setMaximumSize(new java.awt.Dimension(660, 440));
        panelBienvenidos2.setMinimumSize(new java.awt.Dimension(660, 400));
        panelBienvenidos2.setName("ola"); // NOI18N
        panelBienvenidos2.setPreferredSize(new java.awt.Dimension(660, 400));

        labelImgEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Empleado.png"))); // NOI18N
        labelImgEmpleado.setText("jLabel1");
        labelImgEmpleado.setMaximumSize(new java.awt.Dimension(200, 200));
        labelImgEmpleado.setMinimumSize(new java.awt.Dimension(200, 200));
        labelImgEmpleado.setPreferredSize(new java.awt.Dimension(200, 200));

        labelImgCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cliente.png"))); // NOI18N
        labelImgCliente.setText("jLabel2");
        labelImgCliente.setMaximumSize(new java.awt.Dimension(200, 200));
        labelImgCliente.setMinimumSize(new java.awt.Dimension(200, 200));
        labelImgCliente.setPreferredSize(new java.awt.Dimension(200, 200));

        btnEmpleado.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        btnEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        btnEmpleado.setText("Empleado");
        btnEmpleado.setMaximumSize(new java.awt.Dimension(100, 50));
        btnEmpleado.setMinimumSize(new java.awt.Dimension(100, 50));
        btnEmpleado.setPreferredSize(new java.awt.Dimension(100, 50));
        btnEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadoActionPerformed(evt);
            }
        });

        btnCliente.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        btnCliente.setForeground(new java.awt.Color(0, 0, 0));
        btnCliente.setText("Cliente");
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });

        labelEleccion.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        labelEleccion.setForeground(new java.awt.Color(0, 0, 0));
        labelEleccion.setText("Seleccione una opción a continuación:");

        javax.swing.GroupLayout panelBienvenidos2Layout = new javax.swing.GroupLayout(panelBienvenidos2);
        panelBienvenidos2.setLayout(panelBienvenidos2Layout);
        panelBienvenidos2Layout.setHorizontalGroup(
            panelBienvenidos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBienvenidos2Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(labelImgEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(labelImgCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
            .addGroup(panelBienvenidos2Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(btnEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
            .addGroup(panelBienvenidos2Layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(labelEleccion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBienvenidos2Layout.setVerticalGroup(
            panelBienvenidos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBienvenidos2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(labelEleccion)
                .addGap(18, 18, 18)
                .addGroup(panelBienvenidos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelImgEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelImgCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelBienvenidos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        labelImgEmpleado.getAccessibleContext().setAccessibleName("");

        labelBienvenidos.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        labelBienvenidos.setForeground(new java.awt.Color(255, 255, 255));
        labelBienvenidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBienvenidos.setText("Bienvenido a Telefonia");

        javax.swing.GroupLayout panelBeinvenida1Layout = new javax.swing.GroupLayout(panelBeinvenida1);
        panelBeinvenida1.setLayout(panelBeinvenida1Layout);
        panelBeinvenida1Layout.setHorizontalGroup(
            panelBeinvenida1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBeinvenida1Layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addGroup(panelBeinvenida1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBeinvenida1Layout.createSequentialGroup()
                        .addComponent(panelBienvenidos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBeinvenida1Layout.createSequentialGroup()
                        .addComponent(labelBienvenidos, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143))))
        );
        panelBeinvenida1Layout.setVerticalGroup(
            panelBeinvenida1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBeinvenida1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(labelBienvenidos, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBienvenidos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBeinvenida1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBeinvenida1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public frmLoginEmpleado getfrmLoginEmpleado() {
        return frmLoginEmpleado;
    }
    public void setfrmLoginEmpleado(frmLoginEmpleado frmLoginEmpleado) {
        this.frmLoginEmpleado = frmLoginEmpleado;
    }

    public frmLoginCliente getfrmLoginCliente() {
        return frmLoginCliente;
    }
    public void setfrmLoginCliente(frmLoginCliente frmLoginCliente) {
        this.frmLoginCliente = frmLoginCliente;
    }    
    public frmRegisterCliente getFrmRegisterCliente() {
        return frmRegisterCliente;
    }
    public void setFrmRegisterCliente(frmRegisterCliente frmRegisterCliente) {
        this.frmRegisterCliente = frmRegisterCliente;
    }   
  
    private void btnEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadoActionPerformed
        // TODO add your handling code here:
        if (frmLoginEmpleado == null) {
        frmLoginEmpleado = new frmLoginEmpleado();
        frmLoginEmpleado.setfrmBienvenida(this);
        }
        frmLoginEmpleado.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEmpleadoActionPerformed

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        // TODO add your handling code here:
        if (frmLoginCliente == null) {
        frmLoginCliente = new frmLoginCliente();
        frmLoginCliente.setFrmBienvenida(this);
        }
        frmLoginCliente.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBienvenida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnEmpleado;
    private javax.swing.JLabel labelBienvenidos;
    private javax.swing.JLabel labelEleccion;
    private javax.swing.JLabel labelImgCliente;
    private javax.swing.JLabel labelImgEmpleado;
    private javax.swing.JPanel panelBeinvenida1;
    private javax.swing.JPanel panelBienvenidos2;
    // End of variables declaration//GEN-END:variables
}
