/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorCambiar;
import Controlador.ControladorFormularios;
import Controlador.Validaciones;
import javax.swing.JOptionPane;

/**
 *
 * @author megap
 */
public class frmCambio extends javax.swing.JFrame {

    //Atributos de frmCambio
    private frmMisDatos frmEditarDatos;
    private String tipoCambio;
    private String idUsuario;
    
    /**
     * Creates new form frmCambio
     */
    
    //Constructor parametrizado
    public frmCambio(frmMisDatos frmEditarDatos, String tipoCambio, String idUsuario) {
       this.tipoCambio = tipoCambio;
       this.idUsuario = idUsuario;
       this.frmEditarDatos = frmEditarDatos;
       initComponents();
       cambiarLabel();
       setDefaultCloseOperation(frmCambio.DISPOSE_ON_CLOSE);
    }
    public frmCambio(){
        initComponents();
    }

    //Metodos setters y getters
    public frmMisDatos getFrmEditarDatos() {
        return frmEditarDatos;
    }
    public void setFrmEditarDatos(frmMisDatos frmEditarDatos) {
        this.frmEditarDatos = frmEditarDatos;
    }
    public String getTipoCambio() {
        return tipoCambio;
    }
    public void setTipoCambio(String tipoCambio) {
        this.tipoCambio = tipoCambio;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        panelCambio1 = new javax.swing.JPanel();
        panelCambio2 = new javax.swing.JPanel();
        labelContra = new javax.swing.JLabel();
        labelCambiar = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        txtCambiar = new javax.swing.JTextField();
        labelCambio = new javax.swing.JLabel();
        btnCambiar = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Modificar");

        panelCambio1.setBackground(new java.awt.Color(0, 102, 102));

        labelContra.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        labelContra.setText("Contraseña:");

        labelCambiar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        labelCambiar.setText("Contrasena o Email:");

        password.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });

        txtCambiar.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N

        javax.swing.GroupLayout panelCambio2Layout = new javax.swing.GroupLayout(panelCambio2);
        panelCambio2.setLayout(panelCambio2Layout);
        panelCambio2Layout.setHorizontalGroup(
            panelCambio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCambio2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelCambio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(password, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .addComponent(labelContra)
                    .addComponent(labelCambiar)
                    .addComponent(txtCambiar, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        panelCambio2Layout.setVerticalGroup(
            panelCambio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCambio2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelContra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCambiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCambiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        labelCambio.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        labelCambio.setForeground(new java.awt.Color(255, 255, 255));
        labelCambio.setText("Cambiar ...");

        btnCambiar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnCambiar.setText("Cambiar");
        btnCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCambio1Layout = new javax.swing.GroupLayout(panelCambio1);
        panelCambio1.setLayout(panelCambio1Layout);
        panelCambio1Layout.setHorizontalGroup(
            panelCambio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCambio1Layout.createSequentialGroup()
                .addGap(0, 30, Short.MAX_VALUE)
                .addGroup(panelCambio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCambio)
                    .addComponent(panelCambio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
            .addGroup(panelCambio1Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(btnCambiar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCambio1Layout.setVerticalGroup(
            panelCambio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCambio1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCambio)
                .addGap(5, 5, 5)
                .addComponent(panelCambio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCambiar)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCambio1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCambio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed
    
    //Verifica la contrasena y el correo o contrasena a cambiar, si los datos son correctos los cambia
    private void btnCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarActionPerformed
        // TODO add your handling code here:
        String Contrasena = new String(password.getPassword());
        String Cambiar = txtCambiar.getText();
        
        if (Contrasena.isEmpty() || Cambiar.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (tipoCambio.equals("Email")){
            if (!Validaciones.validarEmail(Cambiar)) {
                JOptionPane.showMessageDialog(this, "Correo electrónico inválido.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }   
        frmEditarDatos.actualizarEmail(Cambiar);
        }
        
        ControladorCambiar.cambiarDato(tipoCambio, Contrasena, Cambiar, idUsuario);
        ControladorFormularios.limpiarCampos(this, "");
        this.dispose();
    }//GEN-LAST:event_btnCambiarActionPerformed

    //Cambia de acuerdo a que se presiono en frmMisDatos
    private void cambiarLabel(){
        labelCambio.setText("Cambiar " + tipoCambio);
        labelCambiar.setText(tipoCambio + ":");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCambio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCambio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCambio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCambio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCambio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelCambiar;
    private javax.swing.JLabel labelCambio;
    private javax.swing.JLabel labelContra;
    private javax.swing.JPanel panelCambio1;
    private javax.swing.JPanel panelCambio2;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField txtCambiar;
    // End of variables declaration//GEN-END:variables
}
