/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import Modelo.Cliente;

/**
 *
 * @author megap
 */
public class frmMisDatos extends javax.swing.JFrame {
    
    //Atributos de frmMisDatos
    private frmMenu frmMenu;
    private Cliente Cliente;
    private frmCambio frmCambio;

    /**
     * Creates new form frmSolicitarLinea
     */
    
    //Constructor parametrizado
    public frmMisDatos(Cliente Cliente) {
        initComponents();
        this.Cliente = Cliente;
        mostrarDatos();
        
    }
    public frmMisDatos (){
        initComponents();  
    }

    //Metodos getters y setters
    public frmMenu getFrmMenu() {
        return frmMenu;
    }
    public void setFrmMenu(frmMenu frmMenu) {
        this.frmMenu = frmMenu;
    }  
    public frmCambio getFrmCambio() {
        return frmCambio;
    }
    public void setFrmCambio(frmCambio frmCambio) {
        this.frmCambio = frmCambio;
    } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelMisDatos = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelNombre = new javax.swing.JLabel();
        labelApellidos = new javax.swing.JLabel();
        labelCorreo = new javax.swing.JLabel();
        labelTipoDocu = new javax.swing.JLabel();
        labelFechaNacim = new javax.swing.JLabel();
        labelEstado = new javax.swing.JLabel();
        btnCambiarContra = new javax.swing.JButton();
        btnCambiarCorreo = new javax.swing.JButton();
        labelFechaRegistro = new javax.swing.JLabel();
        labelNDocu = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Datos del Cliente");
        setMinimumSize(new java.awt.Dimension(868, 612));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(868, 612));
        jPanel1.setMinimumSize(new java.awt.Dimension(868, 612));
        jPanel1.setPreferredSize(new java.awt.Dimension(868, 612));

        labelMisDatos.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        labelMisDatos.setForeground(new java.awt.Color(255, 255, 255));
        labelMisDatos.setText("MIS DATOS");

        jPanel2.setPreferredSize(new java.awt.Dimension(798, 376));

        labelNombre.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(0, 0, 0));
        labelNombre.setText("Nombre: ...");

        labelApellidos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelApellidos.setForeground(new java.awt.Color(0, 0, 0));
        labelApellidos.setText("Apellidos: ...");

        labelCorreo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelCorreo.setForeground(new java.awt.Color(0, 0, 0));
        labelCorreo.setText("Mi correo: ....");

        labelTipoDocu.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelTipoDocu.setForeground(new java.awt.Color(0, 0, 0));
        labelTipoDocu.setText("Tipo de Documento: ....");

        labelFechaNacim.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelFechaNacim.setForeground(new java.awt.Color(0, 0, 0));
        labelFechaNacim.setText("Fecha Nacimiento: ....");

        labelEstado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelEstado.setForeground(new java.awt.Color(0, 0, 0));
        labelEstado.setText("Estado: ....");

        btnCambiarContra.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnCambiarContra.setForeground(new java.awt.Color(0, 0, 0));
        btnCambiarContra.setText("Cambiar Contrasena");
        btnCambiarContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarContraActionPerformed(evt);
            }
        });

        btnCambiarCorreo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnCambiarCorreo.setForeground(new java.awt.Color(0, 0, 0));
        btnCambiarCorreo.setText("Cambiar Correo");
        btnCambiarCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarCorreoActionPerformed(evt);
            }
        });

        labelFechaRegistro.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelFechaRegistro.setForeground(new java.awt.Color(0, 0, 0));
        labelFechaRegistro.setText("Fecha de Registro: ....");

        labelNDocu.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelNDocu.setForeground(new java.awt.Color(0, 0, 0));
        labelNDocu.setText("N. Documento: ....");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnCambiarCorreo)
                        .addGap(83, 83, 83)
                        .addComponent(btnCambiarContra))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(labelFechaNacim, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(labelFechaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTipoDocu, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelNDocu, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTipoDocu)
                    .addComponent(labelNDocu))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFechaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFechaNacim))
                .addGap(30, 30, 30)
                .addComponent(labelCorreo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(labelEstado)
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCambiarCorreo)
                    .addComponent(btnCambiarContra))
                .addGap(50, 50, 50))
        );

        btnAtras.setBackground(new java.awt.Color(0, 102, 102));
        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Atras.png"))); // NOI18N
        btnAtras.setBorder(null);
        btnAtras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAtras.setMaximumSize(new java.awt.Dimension(45, 55));
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(249, 249, 249)
                .addComponent(labelMisDatos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(labelMisDatos)
                        .addGap(35, 35, 35)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Metodo que devuelve al anterior frm
    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        frmMenu.setFrmEditarDatos(this);
        frmMenu.setVisible(true);
        this.setVisible(false);      
    }//GEN-LAST:event_btnAtrasActionPerformed

    //Boton que abre un frm para cambiar la contrasena
    private void btnCambiarContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarContraActionPerformed
        // TODO add your handling code here:
        String tipo = "Contrasena";
        frmCambio = new frmCambio(this, tipo, Cliente.getIdUusario());
        frmCambio.setFrmEditarDatos(this);
        frmCambio.setVisible(true);
    }//GEN-LAST:event_btnCambiarContraActionPerformed
    
    //Boton que abre un frm para cambiar el Email
    private void btnCambiarCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarCorreoActionPerformed
        // TODO add your handling code here:
        String tipo = "Email";
        frmCambio = new frmCambio(this, tipo, Cliente.getIdUusario());
        frmCambio.setFrmEditarDatos(this);       
        frmCambio.setVisible(true);
    }//GEN-LAST:event_btnCambiarCorreoActionPerformed
    
    //Metodo que carga los datos del cliente en los labels
    private void mostrarDatos(){
        labelNombre.setText("Nombre: " + Cliente.getNombre());
        labelApellidos.setText("Apellidos: " + Cliente.getApellidoP() + " " + Cliente.getApellidoM());
        labelTipoDocu.setText("Tipo de Documento: " + Cliente.getTipoDocumento());
        labelNDocu.setText("Num. Documento: " + Cliente.getDocumento());
        labelFechaNacim.setText("Fecha Nacimiento: " + Cliente.getFechaNacimiento());
        labelFechaRegistro.setText("Fecha Registro: " + Cliente.getFechaRegistro());
        labelEstado.setText("Estado: " + Cliente.getEstado());
        labelCorreo.setText("Correo: " + Cliente.getEmail());
    }
    
    //Actualiza el Email despues de cambiarlo
    public void actualizarEmail (String Email){
        labelCorreo.setText("Correo: " + Email);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMisDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMisDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMisDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMisDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMisDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnCambiarContra;
    private javax.swing.JButton btnCambiarCorreo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelApellidos;
    private javax.swing.JLabel labelCorreo;
    private javax.swing.JLabel labelEstado;
    private javax.swing.JLabel labelFechaNacim;
    private javax.swing.JLabel labelFechaRegistro;
    private javax.swing.JLabel labelMisDatos;
    private javax.swing.JLabel labelNDocu;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelTipoDocu;
    // End of variables declaration//GEN-END:variables
}
