/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Cliente;
import java.awt.Window;

/**
 *
 * @author megap
 */
public class frmMenu extends javax.swing.JFrame {
    
    //Atributos de frmMenu
    private frmBienvenida frmBienvenida;
    private Cliente Cliente;
    private frmNuevaLinea frmSolicitarLinea;
    private frmMisLineas frmVermisLineas;
    private frmMisDatos frmEditarDatos;
    private frmRecargar frmRecargar;
    private frmPagarFacturas frmPagarLineas;

    /**
     * Creates new form frmMenuCliente
     */
    
    //Constructor parametrizado
    public frmMenu(Cliente Cliente) {
        initComponents();
        this.Cliente = Cliente;
        labelnomCliente.setText(Cliente.Bienvenida());
    }
    
    public frmMenu() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu1 = new javax.swing.JPanel();
        btnInicio = new javax.swing.JButton();
        panelMenu2 = new javax.swing.JPanel();
        labelnomCliente = new javax.swing.JLabel();
        btnVermisLineas = new javax.swing.JButton();
        btnPagarDeudas = new javax.swing.JButton();
        btnCompraryRecargar = new javax.swing.JButton();
        btnVermisDatos = new javax.swing.JButton();
        labelDetalles = new javax.swing.JLabel();
        btnSolicitar = new javax.swing.JButton();
        labelMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Cliente");
        setMaximumSize(new java.awt.Dimension(868, 612));
        setMinimumSize(new java.awt.Dimension(868, 612));

        panelMenu1.setBackground(new java.awt.Color(0, 102, 102));
        panelMenu1.setMaximumSize(new java.awt.Dimension(868, 612));
        panelMenu1.setMinimumSize(new java.awt.Dimension(868, 612));
        panelMenu1.setPreferredSize(new java.awt.Dimension(868, 612));

        btnInicio.setBackground(new java.awt.Color(0, 102, 102));
        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Inicio.png"))); // NOI18N
        btnInicio.setBorder(null);
        btnInicio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInicio.setMaximumSize(new java.awt.Dimension(45, 55));
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        labelnomCliente.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        labelnomCliente.setForeground(new java.awt.Color(0, 0, 0));
        labelnomCliente.setText("Bienvenido .....");

        btnVermisLineas.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnVermisLineas.setForeground(new java.awt.Color(0, 0, 0));
        btnVermisLineas.setText("Ver mis Lineas");
        btnVermisLineas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVermisLineasActionPerformed(evt);
            }
        });

        btnPagarDeudas.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnPagarDeudas.setForeground(new java.awt.Color(0, 0, 0));
        btnPagarDeudas.setText("Pagar mis Lineas");
        btnPagarDeudas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarDeudasActionPerformed(evt);
            }
        });

        btnCompraryRecargar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnCompraryRecargar.setForeground(new java.awt.Color(0, 0, 0));
        btnCompraryRecargar.setText("Comprar/Recargar");
        btnCompraryRecargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompraryRecargarActionPerformed(evt);
            }
        });

        btnVermisDatos.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnVermisDatos.setForeground(new java.awt.Color(0, 0, 0));
        btnVermisDatos.setText("Ver/Editar mis Datos");
        btnVermisDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVermisDatosActionPerformed(evt);
            }
        });

        labelDetalles.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        labelDetalles.setForeground(new java.awt.Color(0, 0, 0));
        labelDetalles.setText("Selecciona una de las siguiente opciones:");

        btnSolicitar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnSolicitar.setForeground(new java.awt.Color(0, 0, 0));
        btnSolicitar.setText("Solicitar Linea");
        btnSolicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenu2Layout = new javax.swing.GroupLayout(panelMenu2);
        panelMenu2.setLayout(panelMenu2Layout);
        panelMenu2Layout.setHorizontalGroup(
            panelMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(panelMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVermisDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelMenu2Layout.createSequentialGroup()
                        .addGroup(panelMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSolicitar, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCompraryRecargar, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(panelMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPagarDeudas, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVermisLineas, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(labelnomCliente)
                    .addComponent(labelDetalles))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        panelMenu2Layout.setVerticalGroup(
            panelMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelnomCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSolicitar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPagarDeudas, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(panelMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCompraryRecargar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVermisLineas, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnVermisDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        labelMenu.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        labelMenu.setForeground(new java.awt.Color(255, 255, 255));
        labelMenu.setText("Menu de Telefonia TellCall");

        javax.swing.GroupLayout panelMenu1Layout = new javax.swing.GroupLayout(panelMenu1);
        panelMenu1.setLayout(panelMenu1Layout);
        panelMenu1Layout.setHorizontalGroup(
            panelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addComponent(labelMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenu1Layout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addComponent(panelMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );
        panelMenu1Layout.setVerticalGroup(
            panelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenu1Layout.createSequentialGroup()
                        .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenu1Layout.createSequentialGroup()
                        .addComponent(labelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(panelMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Metodos getters y setters
    public frmBienvenida getfrmBienvenida() {
        return frmBienvenida;
    }
    public void setfrmBienvenida(frmBienvenida frmBienvenida) {
        this.frmBienvenida = frmBienvenida;
    }     
    public frmNuevaLinea getfrmSolicitarLinea() {
        return frmSolicitarLinea;
    }
    public void setfrmSolicitarLinea(frmNuevaLinea frmSolicitarLinea) {
        this.frmSolicitarLinea = frmSolicitarLinea;
    }  
    public frmMisLineas getfrmVermisLineas() {
        return frmVermisLineas;
    }
    public void setfrmVermisLineas(frmMisLineas frmVermisLineas) {
        this.frmVermisLineas = frmVermisLineas;
    }  
    public frmMisDatos getFrmEditarDatos() {
        return frmEditarDatos;
    }
    public void setFrmEditarDatos(frmMisDatos frmEditarDatos) {
        this.frmEditarDatos = frmEditarDatos;
    }
    public frmRecargar getFrmRecargar() {
        return frmRecargar;
    }
    public void setFrmRecargar(frmRecargar frmRecargar) {
        this.frmRecargar = frmRecargar;
    }
    public frmPagarFacturas getFrmPagarLineas() {
        return frmPagarLineas;
    }
    public void setFrmPagarLineas(frmPagarFacturas frmPagarLineas) {
        this.frmPagarLineas = frmPagarLineas;
    }
    public Cliente getCliente() {
        return Cliente;
    }
    public void setCliente(Cliente Cliente) {
        this.Cliente = Cliente;
    }  
    
    //Metodo que cierra instancias
    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        // TODO add your handling code here:   
        this.dispose();
    
        // Verificar si ya existe una instancia de frmBienvenida
        for (Window window : java.awt.Window.getWindows()) {
            if (window instanceof frmBienvenida) {
                window.dispose();  // Si existe, cerramos la instancia actual de frmBienvenida
            }
        }
    
        frmBienvenida bienvenida = new frmBienvenida();
        bienvenida.setVisible(true);
        
    }//GEN-LAST:event_btnInicioActionPerformed

    //Boton que abre frmPagrFactura
    private void btnPagarDeudasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarDeudasActionPerformed
        // TODO add your handling code here:
        if(frmPagarLineas == null){
            frmPagarLineas = new frmPagarFacturas(Cliente);
            frmPagarLineas.setFrmMenu(this);
        }
        frmPagarLineas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPagarDeudasActionPerformed

    //Boton que abre frmRecargar
    private void btnCompraryRecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompraryRecargarActionPerformed
        // TODO add your handling code here:
        if(frmRecargar == null){
            frmRecargar = new frmRecargar(Cliente);
            frmRecargar.setFrmMenu(this);
        }
        frmRecargar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCompraryRecargarActionPerformed

    //Boton que abre frmMisLineas
    private void btnVermisLineasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVermisLineasActionPerformed
        // TODO add your handling code here:
        if(frmVermisLineas == null){
            frmVermisLineas = new frmMisLineas(Cliente);
            frmVermisLineas.setFrmMenu(this);
        }
        frmVermisLineas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVermisLineasActionPerformed

    //Boton que abre frmMisDatos
    private void btnVermisDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVermisDatosActionPerformed
        // TODO add your handling code here:
        if(frmEditarDatos == null){
            frmEditarDatos = new frmMisDatos(Cliente);
            frmEditarDatos.setFrmMenu(this);
        }
        frmEditarDatos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVermisDatosActionPerformed

    //Boton que abre frmMisDatos
    private void btnSolicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitarActionPerformed
        // TODO add your handling code here:
        if (frmSolicitarLinea == null){
            frmSolicitarLinea = new frmNuevaLinea(Cliente);
            frmSolicitarLinea.setFrmMenu(this);
        }
        frmSolicitarLinea.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSolicitarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompraryRecargar;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnPagarDeudas;
    private javax.swing.JButton btnSolicitar;
    private javax.swing.JButton btnVermisDatos;
    private javax.swing.JButton btnVermisLineas;
    private javax.swing.JLabel labelDetalles;
    private javax.swing.JLabel labelMenu;
    private javax.swing.JLabel labelnomCliente;
    private javax.swing.JPanel panelMenu1;
    private javax.swing.JPanel panelMenu2;
    // End of variables declaration//GEN-END:variables
}
