/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorLogin;
import javax.swing.JOptionPane;
import Controlador.ValidacionesLogin;

/**
 *
 * @author megap
 */
public class frmRegisterCliente extends javax.swing.JFrame {
    
    private frmBienvenida frmBienvenida;
    private frmLoginCliente frmLoginCliente;
    /**
     * Creates new form frmRegisterCliente
     */
    public frmRegisterCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAtras = new javax.swing.JButton();
        labelBienvenidaLogin = new javax.swing.JLabel();
        labelCambiarR = new javax.swing.JLabel();
        btnCambiarR = new javax.swing.JButton();
        panelLoginCliente1 = new javax.swing.JPanel();
        btnVerificarDatosCliente = new javax.swing.JButton();
        labelContra = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelContra1 = new javax.swing.JLabel();
        passwordCliente = new javax.swing.JPasswordField();
        labelContra2 = new javax.swing.JLabel();
        jcbTipDocu = new javax.swing.JComboBox<>();
        txtapellidoM = new javax.swing.JTextField();
        txtapellidoP = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtnumDocumento = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(868, 612));
        setMinimumSize(new java.awt.Dimension(868, 612));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setMaximumSize(new java.awt.Dimension(868, 612));
        jPanel1.setMinimumSize(new java.awt.Dimension(868, 612));
        jPanel1.setPreferredSize(new java.awt.Dimension(868, 612));

        btnAtras.setBackground(new java.awt.Color(0, 102, 102));
        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Atras.png"))); // NOI18N
        btnAtras.setBorder(null);
        btnAtras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAtras.setMaximumSize(new java.awt.Dimension(45, 55));
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        labelBienvenidaLogin.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        labelBienvenidaLogin.setForeground(new java.awt.Color(255, 255, 255));
        labelBienvenidaLogin.setText("Bienvenido");

        labelCambiarR.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        labelCambiarR.setForeground(new java.awt.Color(255, 255, 255));
        labelCambiarR.setText("¿No eres nuevo?");

        btnCambiarR.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        btnCambiarR.setText("Logueate");
        btnCambiarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarRActionPerformed(evt);
            }
        });

        panelLoginCliente1.setPreferredSize(new java.awt.Dimension(557, 414));

        btnVerificarDatosCliente.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        btnVerificarDatosCliente.setForeground(new java.awt.Color(0, 0, 0));
        btnVerificarDatosCliente.setText("Ingresar");
        btnVerificarDatosCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarDatosClienteActionPerformed(evt);
            }
        });

        labelContra.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        labelContra.setForeground(new java.awt.Color(0, 0, 0));
        labelContra.setText("Contrasena:");

        txtNombre.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.setName(""); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nombres:");

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Apellido Materno:");

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Tipo Documento:");

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Apellido Paterno:");

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Num. Documento:");

        labelContra1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        labelContra1.setForeground(new java.awt.Color(0, 0, 0));
        labelContra1.setText("Email:");

        passwordCliente.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        passwordCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordClienteActionPerformed(evt);
            }
        });

        labelContra2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        labelContra2.setForeground(new java.awt.Color(0, 0, 0));
        labelContra2.setText("Fecha Nacimimiento:");

        jcbTipDocu.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jcbTipDocu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DNI", "Pasaporte" }));
        jcbTipDocu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTipDocuActionPerformed(evt);
            }
        });

        txtapellidoM.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        txtapellidoM.setForeground(new java.awt.Color(0, 0, 0));
        txtapellidoM.setName(""); // NOI18N
        txtapellidoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapellidoMActionPerformed(evt);
            }
        });

        txtapellidoP.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        txtapellidoP.setForeground(new java.awt.Color(0, 0, 0));
        txtapellidoP.setName(""); // NOI18N
        txtapellidoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapellidoPActionPerformed(evt);
            }
        });

        txtEmail.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(0, 0, 0));
        txtEmail.setName(""); // NOI18N
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        txtFecha.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        txtFecha.setForeground(new java.awt.Color(0, 0, 0));
        txtFecha.setName(""); // NOI18N
        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });

        txtnumDocumento.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        txtnumDocumento.setForeground(new java.awt.Color(0, 0, 0));
        txtnumDocumento.setName(""); // NOI18N
        txtnumDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumDocumentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLoginCliente1Layout = new javax.swing.GroupLayout(panelLoginCliente1);
        panelLoginCliente1.setLayout(panelLoginCliente1Layout);
        panelLoginCliente1Layout.setHorizontalGroup(
            panelLoginCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginCliente1Layout.createSequentialGroup()
                .addGroup(panelLoginCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLoginCliente1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(panelLoginCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelLoginCliente1Layout.createSequentialGroup()
                                .addComponent(labelContra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(passwordCliente))
                            .addGroup(panelLoginCliente1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(54, 54, 54)
                                .addComponent(txtNombre))
                            .addGroup(panelLoginCliente1Layout.createSequentialGroup()
                                .addComponent(labelContra1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtEmail))
                            .addGroup(panelLoginCliente1Layout.createSequentialGroup()
                                .addComponent(labelContra2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFecha))
                            .addGroup(panelLoginCliente1Layout.createSequentialGroup()
                                .addGroup(panelLoginCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jcbTipDocu, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(panelLoginCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelLoginCliente1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(91, 91, 91))
                                    .addComponent(txtnumDocumento)))
                            .addGroup(panelLoginCliente1Layout.createSequentialGroup()
                                .addGroup(panelLoginCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(txtapellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(panelLoginCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtapellidoM)
                                    .addGroup(panelLoginCliente1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(panelLoginCliente1Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(btnVerificarDatosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        panelLoginCliente1Layout.setVerticalGroup(
            panelLoginCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoginCliente1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panelLoginCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLoginCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLoginCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtapellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtapellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLoginCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLoginCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbTipDocu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnumDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(panelLoginCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelContra1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLoginCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelContra, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLoginCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelContra2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnVerificarDatosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelCambiarR)
                    .addComponent(btnCambiarR))
                .addGap(29, 29, 29)
                .addComponent(panelLoginCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelBienvenidaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(304, 304, 304))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(labelBienvenidaLogin)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelCambiarR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCambiarR)
                        .addGap(128, 128, 128))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelLoginCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(34, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public frmBienvenida getFrmBienvenida() {
        return frmBienvenida;
    }
    public void setFrmBienvenida(frmBienvenida frmBienvenida) {
        this.frmBienvenida = frmBienvenida;
    }
    public frmLoginCliente getFrmLoginCliente() {
        return frmLoginCliente;
    }
    public void setFrmLoginCliente(frmLoginCliente frmLoginCliente) {
        this.frmLoginCliente = frmLoginCliente;
    }
       
    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        frmBienvenida.setFrmRegisterCliente(this);
        frmBienvenida.setVisible(true);
        this.setVisible(false);
        txtNombre.setText("");
        txtEmail.setText("");
        txtFecha.setText("");
        txtapellidoM.setText("");
        txtapellidoP.setText("");
        txtnumDocumento.setText("");
        passwordCliente.setText("");       
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnCambiarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarRActionPerformed
        // TODO add your handling code here:
        frmLoginCliente.setFrmRegisterCliente(this);
        frmLoginCliente.setVisible(true);
        this.setVisible(false);
        txtNombre.setText("");
        txtEmail.setText("");
        txtFecha.setText("");
        txtapellidoM.setText("");
        txtapellidoP.setText("");
        txtnumDocumento.setText("");
        passwordCliente.setText(""); 
    }//GEN-LAST:event_btnCambiarRActionPerformed

    private void btnVerificarDatosClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarDatosClienteActionPerformed
        // TODO add your handling code here:
        String Nombre = txtNombre.getText();
        String apellidoP = txtapellidoP.getText();
        String apellidoM = txtapellidoM.getText();
        String numDocumento = txtnumDocumento.getText();
        String tipoDocumento = jcbTipDocu.getSelectedItem().toString().trim();
        String fechaNacimiento = txtFecha.getText();
        String contrasena = new String(passwordCliente.getPassword());
        String Email = txtEmail.getText();

        if (Nombre.isEmpty() || apellidoP.isEmpty() || numDocumento.isEmpty() || 
            contrasena.isEmpty() || Email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!ValidacionesLogin.validarNombre(Nombre)) {
            JOptionPane.showMessageDialog(this, "Nombre inválido. Debe contener una o dos palabras.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!ValidacionesLogin.validarApellido(apellidoP)) {
            JOptionPane.showMessageDialog(this, "Apellido paterno inválido. Debe contener solo una palabra.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!ValidacionesLogin.validarApellido(apellidoM)) {
            JOptionPane.showMessageDialog(this, "Apellido materno inválido. Debe contener solo una palabra.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!ValidacionesLogin.validarDocumento(numDocumento, tipoDocumento)) {
            JOptionPane.showMessageDialog(this, "Número de documento inválido para el tipo seleccionado.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!ValidacionesLogin.validarEmail(Email)) {
            JOptionPane.showMessageDialog(this, "Correo electrónico inválido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!ValidacionesLogin.validarFechaNacimiento(fechaNacimiento)) {
            JOptionPane.showMessageDialog(this, "Fecha de nacimiento inválida. Formato correcto: dd/MM/yy.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        boolean registrado = ControladorLogin.registrarCliente(Nombre, apellidoP, apellidoM, Email, contrasena, fechaNacimiento, tipoDocumento, numDocumento);

        if (registrado) {
            JOptionPane.showMessageDialog(this, "Cliente registrado correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar el cliente", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnVerificarDatosClienteActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void passwordClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordClienteActionPerformed

    private void txtapellidoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapellidoMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellidoMActionPerformed

    private void txtapellidoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapellidoPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellidoPActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void jcbTipDocuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTipDocuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbTipDocuActionPerformed

    private void txtnumDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumDocumentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegisterCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegisterCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegisterCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegisterCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRegisterCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnCambiarR;
    private javax.swing.JButton btnVerificarDatosCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jcbTipDocu;
    private javax.swing.JLabel labelBienvenidaLogin;
    private javax.swing.JLabel labelCambiarR;
    private javax.swing.JLabel labelContra;
    private javax.swing.JLabel labelContra1;
    private javax.swing.JLabel labelContra2;
    private javax.swing.JPanel panelLoginCliente1;
    private javax.swing.JPasswordField passwordCliente;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtapellidoM;
    private javax.swing.JTextField txtapellidoP;
    private javax.swing.JTextField txtnumDocumento;
    // End of variables declaration//GEN-END:variables
}
